### ISSUE TITLE
CSVMaxCol and MinCol not working

### ISSUE THREAD

**Issue by fab6** [chrisbra/csv.vim#134] opened 2018-08-21 05:46 UTC
Hi,
somehow I get always an error message for different csv files when checking for the largest and smallest number with neovim (app.image):
"Evaluating MaxColumn failed for column 3!"

CSVAnalyze works. Do you have an idea about this error message?
Thanks!

**Comment by chrisbra** [comment] 2018-08-21 07:14
No, please check if this works with Vim. Also please provide the csv file so I can check.

**Comment by fab6** [comment] 2018-08-21 08:26
Hi, with vim 8.01390 same error. A test case is attached; actually it is a quite simple csv file.  CSVAnalyze works in vim as well
[test.csv.txt](https://github.com/chrisbra/csv.vim/files/2305420/test.csv.txt)

**Comment by chrisbra** [comment] 2018-08-21 08:53
thanks, I see the problem. This was caused by the recent refactoring into an autoloadable plugin. Should be fixed now.

**Closed** 2018-08-21 08:52 UTC

**Comment by fab6** [comment] 2018-08-21 11:36
yes, thanks!
For the same case CSVSumCol does not work for the first two columns.
And is there an option to define the row number of the header? I have a lot of csv files with the two top rows as header and only the second row is really relevant.
Thank you!

**Comment by fab6** [comment] 2018-08-22 12:53
ok thanks, great!
